site_name: Python UNLP
theme:
  language: es
  name: "material"
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticy
  palette:
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Inicio: index.md
  - Explicaciones: explicaciones.md
  - Blog:
      - blog/index.md
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
  - md_in_html
  - admonition
  - codehilite
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - sane_lists
plugins:
  - blog
  - search
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: "https://gitlab.catedras.linti.unlp.edu.ar/python-2025/"
    - icon: fontawesome/brands/discord
      link: "#"
    - icon: fontawesome/solid/book
      link: "#"
    - icon: fontawesome/solid/envelope
      link: "mailto: python@info.unlp.edu.ar"
