site_name: Python UNLP
theme:
  name: "material"
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticy
  palette:
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Inicio: index.md
  - Explicaciones: explicaciones.md
  - Guías:
      - guias/01/commands.md
      - guias/02/instalar_python.md
      - guias/03/git.md
      - guias/04/git_basico.md
      - guias/05/ssh.md
      - guias/06/ssh_gitlab.md
      - guias/07/entornos_virtuales.md
      - guias/08/manejo_de_paquetes.md
      - guias/09/guias_de_estilo.md
      - guias/10/merge_request.md
      - guias/11/jupyter_notebook.md
      - guias/12/buenas_practicas.md

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - codehilite
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mkdocs-video
extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.catedras.linti.unlp.edu.ar/python2024/
    - icon: fontawesome/brands/discord
      link: "https://discord.gg/WW2v5Rq3Ke"
    - icon: fontawesome/solid/book
      link: "#"
    - icon: fontawesome/solid/envelope
      link: "mailto: python@info.unlp.edu.ar"
